FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "run", "start"]


# docker build -t (imageName) -f Dockerfile.dev .

# docker run -d -p 4000:3000 --name (containerName) (imageName)