---
# push the docker image to docker hub
name: Deploy docker image to Docker Hub
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build the docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-application -f Dockerfile.dev .

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-application


      
