name: React application build and deploy
on:
  push:
    branches: [ '*' ]
  pull_request:
    types: [closed]
jobs:
  sit:
    name: system integration environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "sit env"
  test:
    name: test environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "Build"
  deploy:
    needs: test
    name: production environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "staging"
