
















name: React application build and deploy
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "Build"
  staging:
    needs: build
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
    - name: Publish app for deploy
      run: echo "Build"
  deploy:
    needs: staging
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
    - name: Publish app for deploy
      run: echo "staging"
