name: React application build and deploy
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
jobs:
  sit:
    name: system integration environment
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "Build"
  test:
    needs: sit
    name: test environment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "Build"
  deploy:
    needs: test
    name: production environment
    if: github.event.pull_request.base.ref == 'test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Publish app for deploy
      run: echo "staging"
